name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      force: ${{ github.event.inputs.force }}
      languages: |
        - python
      mode: direct
      openapi_docs: |
        - https://gist.githubusercontent.com/lbroudoux/75b4ea340d5ddecf9b27a06e7f18ab6d/raw/dc19d8b3354ff8cca459ad79a3196243e11f31d3/weather-forecast-1.0.0-openapi.yaml
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
